#!/bin/bash
# Proper header for a Bash script.

echo "This file was AUTOMATICALLY generated by the list_files.sh script." > notes/file_list.txt

echo "" >> notes/file_list.txt
ls -R1 -I concerns app/controllers >> notes/file_list.txt

echo "" >> notes/file_list.txt
ls -R1 -I concerns app/helpers >> notes/file_list.txt

echo "" >> notes/file_list.txt
ls -R1 -I concerns app/mailers >> notes/file_list.txt

echo "" >> notes/file_list.txt
ls -R1 -I concerns app/models >> notes/file_list.txt

echo "" >> notes/file_list.txt
ls -R1 -I concerns app/views >> notes/file_list.txt

echo "" >> notes/file_list.txt
ls -R1 -I concerns db >> notes/file_list.txt

echo "" >> notes/file_list.txt
ls -R1 -I concerns test >> notes/file_list.txt
