#!/bin/bash
# Proper header for a Bash script.

echo "This file was AUTOMATICALLY generated by the list_files.sh script."

echo
ls -R1 -I concerns app/controllers

echo
ls -R1 -I concerns app/helpers

echo
ls -R1 -I concerns app/mailers

echo
ls -R1 -I concerns app/models

echo
ls -R1 -I concerns app/views

echo
ls -R1 -I concerns db

echo
ls -R1 -I concerns test
