# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 9) do

  create_table "events", :force => true do |t|
    t.column "created_at", :datetime, :null => false
    t.column "scheduled_time", :datetime, :null => false
    t.column "headline", :string, :limit => 200, :default => "", :null => false
    t.column "body", :text, :default => "", :null => false
    t.column "user_id", :integer, :default => 0, :null => false
  end

  create_table "for_hires", :force => true do |t|
    t.column "blurb", :text, :default => "", :null => false
    t.column "created_at", :datetime, :null => false
    t.column "email", :string, :limit => 200, :default => "", :null => false
    t.column "title", :string, :limit => 200, :default => "", :null => false
    t.column "user_id", :integer, :default => 0, :null => false
  end

  create_table "links", :force => true do |t|
    t.column "description", :string
    t.column "url", :string
    t.column "score", :integer, :default => 0
    t.column "clicked", :integer, :default => 0
    t.column "user_id", :integer
    t.column "title", :string
  end

  create_table "list_mails", :force => true do |t|
    t.column "subject", :string, :limit => 256, :default => "", :null => false
    t.column "replyto", :string, :limit => 256
    t.column "from", :string, :limit => 128, :default => "", :null => false
    t.column "to", :string, :limit => 128, :default => "", :null => false
    t.column "stamp", :datetime, :null => false
    t.column "body", :text, :default => "", :null => false
    t.column "mailid", :string, :limit => 256, :default => "", :null => false
    t.column "parent_id", :integer
  end

  create_table "openings", :force => true do |t|
    t.column "created_at", :datetime, :null => false
    t.column "body", :text, :default => "", :null => false
    t.column "headline", :string, :limit => 200, :default => "", :null => false
    t.column "type", :string, :limit => 50, :default => "", :null => false
    t.column "user_id", :integer, :default => 0, :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80, :default => "", :null => false
    t.column "salted_password", :string, :limit => 80, :default => "", :null => false
    t.column "email", :string, :limit => 100, :default => "", :null => false
    t.column "firstname", :string, :limit => 100, :default => "", :null => false
    t.column "lastname", :string, :limit => 100, :default => "", :null => false
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "verified", :boolean, :default => false, :null => false
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "deleted", :boolean, :default => false
  end

end
